require("dotenv").config();
const express=require("express");const http=require("http");const cors=require("cors");const {Server}=require("socket.io");const connectDB=require("./config/db");const startJobs=require("./jobs/expiryJobs");
const app=express();const server=http.createServer(app);
const io=new Server(server,{cors:{origin:process.env.CLIENT_URL||"http://localhost:5173",methods:["GET","POST","PUT","PATCH","OPTIONS"]}});
app.use(cors({origin:process.env.CLIENT_URL||"http://localhost:5173"}));app.use(express.json());
app.get("/",(req,res)=>res.json({message:"Ticket Booking API is running"}));app.get("/api/health",(req,res)=>res.json({ok:true}));
app.use("/api/auth",require("./routes/authRoutes"));app.use("/api/venues",require("./routes/venueRoutes"));app.use("/api/events",require("./routes/eventRoutes"));
app.use("/api/seats",require("./routes/seatRoutes"));app.use("/api/bookings",require("./routes/bookingRoutes"));app.use("/api/waitlist",require("./routes/waitlistRoutes"));
io.on("connection",socket=>{socket.on("join-show",id=>socket.join(`show:${id}`));});
app.set("io",io);
connectDB().then(()=>{startJobs(io);const port=process.env.PORT||5000;server.listen(port,()=>console.log(`API running on ${port}`));}).catch(e=>{console.error(e);process.exit(1)});
